// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-draft-index.ts
// Draft battle seeds discovered by publishState !== 'published'.
import type { Battle } from '@yonokomae/types';
import d0 from './agile-vs-stable-battle.ja';
import d1 from './civic-will-battle.ja';
import d2 from './commuter-destination-battle.ja';
import d3 from './finance-strategy-battle.ja';
import d4 from './financial-philosophy-battle.ja';
import d5 from './function-vs-niche-battle.ja';
import d6 from './historical-feud-vs-independence.ja';
import d7 from './legacy-transfer-battle.ja';
import d8 from './media-vs-tradition-battle.ja';
import d9 from './planning-vs-spontaneity-battle.ja';
import d10 from './population-dynamics-battle.ja';
import d11 from './service-optimization-battle.ja';
import d12 from './space-philosophy-battle.ja';
import d13 from './urban-model-battle.ja';

export const draftBattleMap: Record<string, Battle> = {
  'agile-vs-stable-battle.ja.ts': d0,
  'civic-will-battle.ja.ts': d1,
  'commuter-destination-battle.ja.ts': d2,
  'finance-strategy-battle.ja.ts': d3,
  'financial-philosophy-battle.ja.ts': d4,
  'function-vs-niche-battle.ja.ts': d5,
  'historical-feud-vs-independence.ja.ts': d6,
  'legacy-transfer-battle.ja.ts': d7,
  'media-vs-tradition-battle.ja.ts': d8,
  'planning-vs-spontaneity-battle.ja.ts': d9,
  'population-dynamics-battle.ja.ts': d10,
  'service-optimization-battle.ja.ts': d11,
  'space-philosophy-battle.ja.ts': d12,
  'urban-model-battle.ja.ts': d13,
};
