// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-battle-index.ts
// Source of truth: publishState property inside each battle seed file.
// Timestamp: 2025-09-09T09:08:50.148Z
import type { Battle } from '@yonokomae/types';
import b0 from '../theme/community/adjacent-municipalities.ja.js';
import b1 from '../theme/development/agriculture.ja.js';
import b2 from '../theme/information/ai-oracle.ja.js';
import b3 from '../theme/history/ancient-life-battle.ja.js';
import b4 from '../theme/development/area-comparison.ja.js';
import b5 from '../theme/figures/celebrity-battle.ja.js';
import b6 from '../theme/technology/child-safety-battle.ja.js';
import b7 from '../theme/history/city-name-origin.ja.js';
import b8 from '../theme/technology/civic-tech-battle.ja.js';
import b9 from '../theme/technology/coder-dojo-battle.ja.js';
import b10 from '../theme/development/commuting-flows.ja.js';
import b11 from '../theme/culture/culture-battle.ja.js';
import b12 from '../theme/information/data-ghost-hunt.ja.js';
import b13 from '../theme/development/density-battle.ja.js';
import b14 from '../theme/development/development-battle.ja.js';
import b15 from '../theme/technology/disaster-simulation-battle.ja.js';
import b16 from '../theme/figures/edo-era-heroes.ja.js';
import b17 from '../theme/development/fisheries.ja.js';
import b18 from '../theme/development/flood-battle.ja.js';
import b19 from '../theme/development/geomorphology-hydrology.ja.js';
import b20 from '../theme/history/hwmb-komae-independence.ja.js';
import b21 from '../theme/history/hwmb-merger-and-independence.ja.js';
import b22 from '../theme/history/hwmb-merger-of-glory.ja.js';
import b23 from '../theme/community/ikada-race.ja.js';
import b24 from '../theme/finance/industry-growth.ja.js';
import b25 from '../theme/technology/kids-tech-battle.ja.js';
import b26 from '../theme/finance/local-currency-battle.ja.js';
import b27 from '../theme/culture/metaverse-shrine.ja.js';
import b28 from '../theme/development/meteorology.ja.js';
import b29 from '../theme/technology/parenting-robot-battle.ja.js';
import b30 from '../theme/development/population-trends.ja.js';
import b31 from '../theme/technology/robot-ethics.ja.js';
import b32 from '../theme/history/ruins-battle.ja.js';
import b33 from '../theme/history/sengoku-territory.ja.js';
import b34 from '../theme/figures/showa-superstar-battle.ja.js';
import b35 from '../theme/culture/snack-battle.ja.js';
import b36 from '../theme/information/sns-truth-vs-lies.ja.js';
import b37 from '../theme/finance/socioeconomic.ja.js';
import b38 from '../theme/technology/taste-algorithm.ja.js';
import b39 from '../theme/development/transportation-hub-battle.ja.js';
import b40 from '../theme/development/underground-conspiracy.ja.js';
import b41 from '../theme/development/water-resource-battle.ja.js';
import b42 from '../theme/information/wikipedia-ja-battle.ja.js';
import b43 from '../__drafts/agile-vs-stable-battle.ja.js';
import b44 from '../__drafts/civic-will-battle.ja.js';
import b45 from '../__drafts/commuter-destination-battle.ja.js';
import b46 from '../__drafts/finance-strategy-battle.ja.js';
import b47 from '../__drafts/financial-philosophy-battle.ja.js';
import b48 from '../__drafts/function-vs-niche-battle.ja.js';
import b49 from '../__drafts/historical-feud-vs-independence.ja.js';
import b50 from '../__drafts/legacy-transfer-battle.ja.js';
import b51 from '../__drafts/media-vs-tradition-battle.ja.js';
import b52 from '../__drafts/planning-vs-spontaneity-battle.ja.js';
import b53 from '../__drafts/population-dynamics-battle.ja.js';
import b54 from '../__drafts/service-optimization-battle.ja.js';
import b55 from '../__drafts/space-philosophy-battle.ja.js';
import b56 from '../__drafts/urban-model-battle.ja.js';

// Backward compatible named maps
export const publishedBattleMap: Record<string, Battle> = {
  'adjacent-municipalities.ja.ts': b0,
  'agriculture.ja.ts': b1,
  'ai-oracle.ja.ts': b2,
  'ancient-life-battle.ja.ts': b3,
  'area-comparison.ja.ts': b4,
  'celebrity-battle.ja.ts': b5,
  'child-safety-battle.ja.ts': b6,
  'city-name-origin.ja.ts': b7,
  'civic-tech-battle.ja.ts': b8,
  'coder-dojo-battle.ja.ts': b9,
  'commuting-flows.ja.ts': b10,
  'culture-battle.ja.ts': b11,
  'data-ghost-hunt.ja.ts': b12,
  'density-battle.ja.ts': b13,
  'development-battle.ja.ts': b14,
  'disaster-simulation-battle.ja.ts': b15,
  'edo-era-heroes.ja.ts': b16,
  'fisheries.ja.ts': b17,
  'flood-battle.ja.ts': b18,
  'geomorphology-hydrology.ja.ts': b19,
  'hwmb-komae-independence.ja.ts': b20,
  'hwmb-merger-and-independence.ja.ts': b21,
  'hwmb-merger-of-glory.ja.ts': b22,
  'ikada-race.ja.ts': b23,
  'industry-growth.ja.ts': b24,
  'kids-tech-battle.ja.ts': b25,
  'local-currency-battle.ja.ts': b26,
  'metaverse-shrine.ja.ts': b27,
  'meteorology.ja.ts': b28,
  'parenting-robot-battle.ja.ts': b29,
  'population-trends.ja.ts': b30,
  'robot-ethics.ja.ts': b31,
  'ruins-battle.ja.ts': b32,
  'sengoku-territory.ja.ts': b33,
  'showa-superstar-battle.ja.ts': b34,
  'snack-battle.ja.ts': b35,
  'sns-truth-vs-lies.ja.ts': b36,
  'socioeconomic.ja.ts': b37,
  'taste-algorithm.ja.ts': b38,
  'transportation-hub-battle.ja.ts': b39,
  'underground-conspiracy.ja.ts': b40,
  'water-resource-battle.ja.ts': b41,
  'wikipedia-ja-battle.ja.ts': b42,
};
export const draftBattleMap: Record<string, Battle> = {
  'agile-vs-stable-battle.ja.ts': b43,
  'civic-will-battle.ja.ts': b44,
  'commuter-destination-battle.ja.ts': b45,
  'finance-strategy-battle.ja.ts': b46,
  'financial-philosophy-battle.ja.ts': b47,
  'function-vs-niche-battle.ja.ts': b48,
  'historical-feud-vs-independence.ja.ts': b49,
  'legacy-transfer-battle.ja.ts': b50,
  'media-vs-tradition-battle.ja.ts': b51,
  'planning-vs-spontaneity-battle.ja.ts': b52,
  'population-dynamics-battle.ja.ts': b53,
  'service-optimization-battle.ja.ts': b54,
  'space-philosophy-battle.ja.ts': b55,
  'urban-model-battle.ja.ts': b56,
};
export const reviewBattleMap: Record<string, Battle> = {};
export const archivedBattleMap: Record<string, Battle> = {};
export const battleMapsByPublishState = {
  'published': publishedBattleMap,
  'draft': draftBattleMap,
  'review': reviewBattleMap,
  'archived': archivedBattleMap,
} as const;
export const publishStateKeys = ['published', 'draft', 'review', 'archived'] as const;
export type PublishStateKey = typeof publishStateKeys[number];
export const allBattleMap: Record<string, Battle> = Object.values(battleMapsByPublishState).reduce((acc, m) => Object.assign(acc, m), {} as Record<string, Battle>);
export const battleSeedsByPublishState: Record<PublishStateKey, Battle[]> =
  (Object.keys(battleMapsByPublishState) as PublishStateKey[]).reduce(
    (acc, key) => {
      acc[key] = Object.values(battleMapsByPublishState[key]);
      return acc;
    },
    {} as Record<PublishStateKey, Battle[]>,
  );
// Grouping by themeId (stable ordering by battle id) for UI layer convenience
export const battlesByThemeId: Record<string, Battle[]> = Object.values(allBattleMap).reduce(
  (acc, b) => {
    (acc[b.themeId] ||= []).push(b);
    return acc;
  },
  {} as Record<string, Battle[]>,
);
for (const key of Object.keys(battlesByThemeId)) {
  const list = battlesByThemeId[key];
  if (list) {
    list.sort((a, b) => a.id.localeCompare(b.id));
  }
}
export const themeIds = Object.keys(battlesByThemeId).sort();
export type ThemeId = keyof typeof battlesByThemeId;
